/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* EMERGENCY APP*/
export const EMERGENCY_GET_LIST = "EMERGENCY_GET_LIST";
export const EMERGENCY_GET_LIST_SUCCESS = "EMERGENCY_GET_LIST_SUCCESS";
export const EMERGENCY_GET_LIST_ERROR = "EMERGENCY_GET_LIST_ERROR";
export const EMERGENCY_GET_LIST_WITH_FILTER = "EMERGENCY_GET_LIST_WITH_FILTER";
export const EMERGENCY_GET_LIST_WITH_ORDER = "EMERGENCY_GET_LIST_WITH_ORDER";
export const EMERGENCY_GET_LIST_SEARCH = "EMERGENCY_GET_LIST_SEARCH";
export const EMERGENCY_ADD_ITEM = "EMERGENCY_ADD_ITEM";
export const EMERGENCY_ADD_ITEM_SUCCESS = "EMERGENCY_ADD_ITEM_SUCCESS";
export const EMERGENCY_ADD_ITEM_ERROR = "EMERGENCY_ADD_ITEM_ERROR";
export const EMERGENCY_SELECTED_ITEMS_CHANGE = "EMERGENCY_SELECTED_ITEMS_CHANGE";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./emergency/actions";